// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/auth/github.tsx";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/ledger/[id].tsx";
import * as $4 from "./routes/login.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/auth/github.tsx": $1,
    "./routes/index.tsx": $2,
    "./routes/ledger/[id].tsx": $3,
    "./routes/login.tsx": $4,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
